import Navbar01 from "./navbar-01/Navbar01";import Navbar02 from "./navbar-02/Navbar02";import Navbar03 from "./navbar-03/Navbar03";import Navbar04 from "./navbar-04/Navbar04";import Navbar05 from "./navbar-05/Navbar05";import Navbar06 from "./navbar-06/Navbar06";import Navbar07 from "./navbar-07/Navbar07";import Navbar08 from "./navbar-08/Navbar08";import Navbar09 from "./navbar-09/Navbar09";import Navbar10 from "./navbar-10/Navbar10";import Navbar11 from "./navbar-11/Navbar11";import Navbar12 from "./navbar-12/Navbar12";import Navbar13 from "./navbar-13/Navbar13";import Navbar14 from "./navbar-14/Navbar14";
import Navbar15 from "./navbar-15/Navbar15";import Navbar16 from "./navbar-16/Navbar16";import Navbar17 from "./navbar-17/Navbar17";import Navbar18 from "./navbar-18/Navbar18";import Navbar19 from "./navbar-19/Navbar19";import Navbar20 from "./navbar-20/Navbar20";import Navbar21 from "./navbar-21/Navbar21";import Navbar22 from "./navbar-22/Navbar22";import Navbar23 from "./navbar-23/Navbar23";import Navbar24 from "./navbar-24/Navbar24";import Navbar25 from "./navbar-25/Navbar25";import Navbar26 from "./navbar-26/Navbar26";import Navbar27 from "./navbar-27/Navbar27";import Navbar28 from "./navbar-28/Navbar28";import Navbar29 from "./navbar-29/Navbar29";import Navbar30 from "./navbar-30/Navbar30";import Navbar31 from "./navbar-31/Navbar31";
import Navbar32 from "./navbar-32/Navbar32";import Navbar33 from "./navbar-33/Navbar33";import Navbar34 from "./navbar-34/Navbar34";import Navbar35 from "./navbar-35/Navbar35";import Navbar36 from "./navbar-36/Navbar36";import Navbar37 from "./navbar-37/Navbar37";import Navbar38 from "./navbar-38/Navbar38";import Navbar39 from "./navbar-39/Navbar39";import Navbar40 from "./navbar-40/Navbar40";import Navbar41 from "./navbar-41/Navbar41";import Navbar42 from "./navbar-42/Navbar42";import Navbar43 from "./navbar-43/Navbar43";import Navbar44 from "./navbar-44/Navbar44";import Navbar45 from "./navbar-45/Navbar45";
import Navbar46 from "./navbar-46/Navbar46";import Navbar47 from "./navbar-47/Navbar47";import Navbar48 from "./navbar-48/Navbar48";import Navbar49 from "./navbar-49/Navbar49";import Navbar50 from "./navbar-50/Navbar50";import Navbar51 from "./navbar-51/Navbar51";import Navbar52 from "./navbar-52/Navbar52";import Navbar53 from "./navbar-53/Navbar53";
export const navbars=[
{id:"01",name:"Milky Way",source:"Component 11",Component:Navbar01},{id:"02",name:"All News",source:"Component 46",Component:Navbar02},{id:"03",name:"EasWorks",source:"Component 47",Component:Navbar03},{id:"04",name:"Monogram",source:"Component 48",Component:Navbar04},{id:"05",name:"Object3D",source:"Component 49",Component:Navbar05},{id:"06",name:"NeoVR",source:"Component 51",Component:Navbar06},{id:"07",name:"Wallet US",source:"Component 52",Component:Navbar07},{id:"08",name:"Rigxr",source:"Component 53",Component:Navbar08},{id:"09",name:"Full Paint",source:"Component 54",Component:Navbar09},{id:"10",name:"The Types",source:"Component 57",Component:Navbar10},{id:"11",name:"PUPSS Amber",source:"Component 58",Component:Navbar11},{id:"12",name:"PUPSS Profile",source:"Component 59",Component:Navbar12},{id:"13",name:"Skinloves",source:"Component 61",Component:Navbar13},{id:"14",name:"Arizona Coffee",source:"Component 250",Component:Navbar14},
{id:"15",name:"Designmes",source:"Frame",Component:Navbar15},{id:"16",name:"Rozes Shop",source:"Header",Component:Navbar16},{id:"17",name:"Healthy Ways",source:"Navbar",Component:Navbar17},{id:"18",name:"GrandMas",source:"NavBar (1)",Component:Navbar18},{id:"19",name:"Modern Wear",source:"Navbar-1",Component:Navbar19},{id:"20",name:"Moras Ranking",source:"NavBar-1 (2)",Component:Navbar20},{id:"21",name:"Nova’84",source:"Navbar-2",Component:Navbar21},{id:"22",name:"BigDesigner",source:"NavBar-2 (3)",Component:Navbar22},{id:"23",name:"Love and Wear",source:"Navbar-3",Component:Navbar23},{id:"24",name:"Menu Cart",source:"Navbar-4",Component:Navbar24},{id:"25",name:"One and Only Drinks",source:"Navbar-5",Component:Navbar25},{id:"26",name:"Homestyle",source:"Navbar-6",Component:Navbar26},{id:"27",name:"Photoroom",source:"Navigation",Component:Navbar27},{id:"28", name:"Lumina AI", source:"Floating Glass", Component:Navbar28},{id:"29", name:"Vogue Design", source:"Split Centered", Component:Navbar29},{id:"30", name:"Zenith Sidebar", source:"Vertical Navigation", Component:Navbar30},{ id: "31",  name: "Tech-X Mega",  source: "Mega Menu",  Component: Navbar31},
{id:"32", name:"Infinity Bottom", source:"Bottom Navigation", Component:Navbar32},  {id: "33", name: "Overlay Portfolio",source: "Full-Screen Menu",Component: Navbar33 },  { id: "34", name: "iFluid", source: "Dynamic Island", Component: Navbar34 },  { id: "35", name: "CoinEdge", source: "Web3 Header", Component: Navbar35 },  { id: "36", name: "SoftBase", source: "Neumorphic UI", Component: Navbar36 },  { id: "37", name: "MacSys", source: "Glassmorphism", Component: Navbar37 },  { id: "38", name: "RetroBlock", source: "Neo-Brutalism", Component: Navbar38 },  { id: "39", name: "EduPath", source: "Progress Bar Nav", Component: Navbar39 },  { id: "40", name: "HomeFindr", source: "Integrated Search", Component: Navbar40 },  { id: "41", name: "ConnectX", source: "Icon-Only Header", Component: Navbar41 },  { id: "42", name: "QuickBite", source: "Location-First Split", Component: Navbar42 },  { id: "43", name: "CyberPlay", source: "Cyberpunk Geometry", Component: Navbar43 },  { id: "44", name: "DailyPulse", source: "Double-Deck Ticker", Component: Navbar44 },  { id: "45", name: "DevStream", source: "Command Palette Docs", Component: Navbar45 },
  { id: "46", name: "AdminPro", source: "Collapsible Left Sidebar", Component: Navbar46 },  { id: "47", name: "ShopRight", source: "Off-Canvas Drawer (Cart)", Component: Navbar47 },  { id: "48", name: "GlobeTrotter", source: "Multi-Language & Currency Header", Component: Navbar48 },  { id: "49", name: "SoundWave", source: "Audio Player Integrated Header", Component: Navbar49 },  { id: "50", name: "TYPEFace", source: "Hero-Sized Typographic Header", Component: Navbar50 },  { id: "51", name: "RewardMe", source: "Gamification Header", Component: Navbar51 },  { id: "52", name: "ClearView", source: "Accessibility-First Header", Component: Navbar52 },  { id: "53", name: "SmartScroll", source: "Contextual Auto-Hide Menu", Component: Navbar53 },




];
